### ISSUE TITLE
A valid puzzle program could not be created for the given arguments and the selected wallet.

### ISSUE THREAD

**Issue by Somnusochi** [prodchia/easy_fd_cli#2]
![image](https://user-images.githubusercontent.com/14160184/131229019-03f3cffa-dabe-4510-abdc-930726537fb0.png)

it doesn’t seem to work.how is it correct?Thx!!!

**Comment by Nirvana2211** [comment]
There definitely seems to be a problem with the parameters you have entered in the config file. Please check the pool address, launcher id and  fingerprint.
